name: Synchronize Todoist
on:
  schedule:
   - cron: "*/30 * * * *"
  workflow_dispatch:
    

jobs:
  sync_issues:
    name: Synchronize // ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Issues
            query: updated:>2021-04-01 archived:false sort:updated-desc assignee:cobraz -label:backlog
            key: generic
          - name: Pull Requests
            query: is:pr updated:>2021-04-01 archived:false sort:updated-desc review-requested:cobraz -label:backlog
            key: pr
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - name: Download cache
        id: cache
        uses: actions/cache@v2
        with:
          key: ${{ matrix.key }}
          path: ./sync.json.enc
      
      - name: Decrypt sync
        if: steps.cache.outputs.cache-hit == 'true'
        run: openssl enc -in ./sync.json.enc -d -pbkdf2 -pass pass:${{ secrets.TODOIST_TOKEN }} -out sync.json

      - name: Sync issues
        if: always()
        id: sync
        uses: ./
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          todoist-token: ${{ secrets.TODOIST_TOKEN }}
          query: ${{ matrix.query }}
          sync-file-name: ./sync.json
      
      - name: Encrypt sync
        if: always() && steps.sync.outputs.has-changed == 'true'
        run: openssl enc -in sync.json -pbkdf2 -pass pass:${{ secrets.TODOIST_TOKEN }} -out sync.json.enc